listen_addresses = '*'
max_connections = 100
ssl = false
io_workers = 32
shared_buffers = 128MB
work_mem = 4MB
maintenance_work_mem = 64MB
wal_level = minimal
synchronous_commit = off
checkpoint_completion_target = 0.9
max_wal_senders = 0
random_page_cost = 2
effective_cache_size = 512MB
log_line_prefix = '%t '
track_activity_query_size = 2048
max_pred_locks_per_transaction = 256
